name: Cargo Checks

on: [push, pull_request]

jobs:
  check:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.6.0
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ply six

      - name: Run the generator
        run: python generate.py

      - name: Check generated files against repo
        run: if [[ ! -z `git status --porcelain=v1` ]]; then echo "::error::Workspace is dirty after running generator. Did you remember to check in the generated files?"; exit 1; fi

      - name: Install MSRV toolchain
        run: rustup install 1.63.0 --profile minimal

      - name: Run cargo test
        run: rustup run 1.63.0 cargo test

      - name: Install nightly toolchain
        run: |
          rustup install nightly --profile minimal
          rustup component add clippy --toolchain nightly

      - name: Run clippy
        run: rustup run nightly cargo clippy --all-targets --all-features -- --deny warnings
