name: Cargo Checks

on: [push, pull_request]

jobs:
  check:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging ply six

      - name: Run the generator
        run: python generate.py

      - name: Check generated files against repo
        run: if [[ ! -z `git status --porcelain=v1` ]]; then echo "::error::Workspace is dirty after running generator. Did you remember to check in the generated files?"; exit 1; fi

      - name: Install MSRV toolchain
        run: rustup install 1.75.0 --profile minimal

      - name: Run cargo test
        run: rustup run 1.75.0 cargo test --all-features

      - name: Install nightly toolchain
        run: |
          rustup install nightly --profile minimal
          rustup component add clippy --toolchain nightly

      - name: Run clippy
        run: rustup run nightly cargo clippy --all-targets --all-features -- --deny warnings

      - name: Run clippy with minimal features (sync)
        run: rustup run nightly cargo clippy --no-default-features --features sync_routes,dbx_files

      - name: Run clippy with minimal features (async)
        run: rustup run nightly cargo clippy --no-default-features --features default_async_client,dbx_files
